<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-20T16:33:17 IST" name="Suite" finished-at="2025-07-20T16:33:17 IST" duration-ms="88">
    <groups>
    </groups>
    <test started-at="2025-07-20T16:33:17 IST" name="Test" finished-at="2025-07-20T16:33:17 IST" duration-ms="88">
      <class name="testAnnotationDemo.DependSOnMethods">
        <test-method signature="openapp()[pri:0, instance:testAnnotationDemo.DependSOnMethods@11392934]" started-at="2025-07-20T16:33:17 IST" name="openapp" finished-at="2025-07-20T16:33:17 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="login()[pri:1, instance:testAnnotationDemo.DependSOnMethods@11392934]" started-at="2025-07-20T16:33:17 IST" name="login" finished-at="2025-07-20T16:33:17 IST" depends-on-methods="testAnnotationDemo.DependSOnMethods.openapp" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testAnnotationDemo.DependSOnMethods.login(DependSOnMethods.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="search()[pri:0, instance:testAnnotationDemo.DependSOnMethods@11392934]" started-at="2025-07-20T16:33:17 IST" name="search" finished-at="2025-07-20T16:33:17 IST" depends-on-methods="testAnnotationDemo.DependSOnMethods.login" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testAnnotationDemo.DependSOnMethods.search() on instance testAnnotationDemo.DependSOnMethods@11392934 depends on not successfully finished methods 
[testAnnotationDemo.DependSOnMethods.login() on instance testAnnotationDemo.DependSOnMethods@11392934]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testAnnotationDemo.DependSOnMethods.search() on instance testAnnotationDemo.DependSOnMethods@11392934 depends on not successfully finished methods 
[testAnnotationDemo.DependSOnMethods.login() on instance testAnnotationDemo.DependSOnMethods@11392934]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method signature="advancedSearch()[pri:1, instance:testAnnotationDemo.DependSOnMethods@11392934]" started-at="2025-07-20T16:33:17 IST" name="advancedSearch" finished-at="2025-07-20T16:33:17 IST" depends-on-methods="testAnnotationDemo.DependSOnMethods.search, testAnnotationDemo.DependSOnMethods.login" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testAnnotationDemo.DependSOnMethods.advancedSearch() on instance testAnnotationDemo.DependSOnMethods@11392934 depends on not successfully finished methods 
[testAnnotationDemo.DependSOnMethods.search() on instance testAnnotationDemo.DependSOnMethods@11392934
testAnnotationDemo.DependSOnMethods.login() on instance testAnnotationDemo.DependSOnMethods@11392934]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testAnnotationDemo.DependSOnMethods.advancedSearch() on instance testAnnotationDemo.DependSOnMethods@11392934 depends on not successfully finished methods 
[testAnnotationDemo.DependSOnMethods.search() on instance testAnnotationDemo.DependSOnMethods@11392934
testAnnotationDemo.DependSOnMethods.login() on instance testAnnotationDemo.DependSOnMethods@11392934]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- advancedSearch -->
        <test-method signature="logout()[pri:2, instance:testAnnotationDemo.DependSOnMethods@11392934]" started-at="2025-07-20T16:33:17 IST" name="logout" finished-at="2025-07-20T16:33:17 IST" depends-on-methods="testAnnotationDemo.DependSOnMethods.login" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testAnnotationDemo.DependSOnMethods.logout() on instance testAnnotationDemo.DependSOnMethods@11392934 depends on not successfully finished methods 
[testAnnotationDemo.DependSOnMethods.login() on instance testAnnotationDemo.DependSOnMethods@11392934]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testAnnotationDemo.DependSOnMethods.logout() on instance testAnnotationDemo.DependSOnMethods@11392934 depends on not successfully finished methods 
[testAnnotationDemo.DependSOnMethods.login() on instance testAnnotationDemo.DependSOnMethods@11392934]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- testAnnotationDemo.DependSOnMethods -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
